spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HarusHoChiHo/springboot.git
          username: harushochiho
          password: 9t7cm4rh
          search-paths: spring-cloud-config-server
          defaultLabel: springbootms
              

server:
  port: 8888
