spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:HarusHoChiHo/springboot.git
          search-paths:
            - spring-cloud-config-server/git-localconfig-repo
              

server:
  port: 8888
